import { generateScale, getSemanticTokens, hexToOklch } from './color'
import { generateRadiusScale, type RadiusMode } from './radius'
import { fontFamilyValue, getFontDef } from './fonts'
import { generateShadowTokens, SHADOW_MULTIPLIERS, type ShadowIntensity } from './shadow'
import { getComponentSpacingTokens, getSpacingScale, type SpacingMode } from './spacing'
import { generateMotionTokens, type MotionMode } from './motion'

function scaleToVars(prefix: string, scale: Record<string, string>): string {
  return Object.entries(scale)
    .map(([step, val]) => `  --color-${prefix}-${step}: ${val};`)
    .join('\n')
}

function tokensToVars(tokens: Record<string, string>): string {
  return Object.entries(tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')
}

export function buildExportCSS(input: {
  brandColor: string
  secondaryColor: string
  baseColor: string
  radiusMode: RadiusMode
  shadowMode: ShadowIntensity
  spacingMode: SpacingMode
  motionMode: MotionMode
  roundIconButtons: boolean
  headingFont: string
  bodyFont: string
}): string {
  const brandScale = generateScale(input.brandColor, false)
  const secondaryScale = generateScale(input.secondaryColor, false)
  const baseScale = generateScale(input.baseColor, true)
  const brandHue = hexToOklch(input.brandColor).h
  const { light, dark } = getSemanticTokens(brandHue)
  const multiplier = SHADOW_MULTIPLIERS[input.shadowMode]
  const motionTokens = generateMotionTokens(input.motionMode)
  const lightTokens = { ...light, ...generateShadowTokens(brandHue, 'light', multiplier), ...motionTokens }
  const darkTokens  = { ...dark,  ...generateShadowTokens(brandHue, 'dark',  multiplier), ...motionTokens }
  const radius = generateRadiusScale(input.radiusMode)
  const spacingScale = getSpacingScale(input.spacingMode)
  const spacingTokens = getComponentSpacingTokens(spacingScale)

  const headingDef = getFontDef(input.headingFont)
  const bodyDef = getFontDef(input.bodyFont)
  const iconButtonRadius = input.roundIconButtons ? radius.pill : radius.md

  return `/* Generated by Design System Builder */

:root {
  /* Brand Color Scale */
${scaleToVars('brand', brandScale)}

  /* Secondary Color Scale */
${scaleToVars('secondary', secondaryScale)}

  /* Base / Neutral Scale */
${scaleToVars('base', baseScale)}

  /* Semantic Tokens */
${tokensToVars(lightTokens)}

  /* Typography */
  --font-heading: ${fontFamilyValue(input.headingFont, headingDef.category)};
  --font-sans: ${fontFamilyValue(input.bodyFont, bodyDef.category)};

  /* Spacing */
${tokensToVars(spacingTokens)}

  /* Border Radius */
  --radius-xs: ${radius.xs};
  --radius-sm: ${radius.sm};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-xl: ${radius.xl};
  --radius-pill: ${radius.pill};
  --radius-icon-button: ${iconButtonRadius};
}

.dark {
${tokensToVars(darkTokens)}
}`
}
